#!/usr/bin/env ruby

lib_path = File.dirname(__FILE__) + '/../lib'
if File.exist?(lib_path)
  $LOAD_PATH << lib_path
end

require 'secrets/cipher/base64'

if ARGV.include?('--generate-secret')
  puts Secrets::Cipher::Base64.create_secret
end
