#!/usr/bin/env ruby

lib_path = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH << lib_path if File.exist?(lib_path) && !$LOAD_PATH.include?(lib_path)

require 'secrets'

Secrets::App::CLI.new(ARGV.dup).run
