#!/usr/bin/env ruby

lib_path = File.expand_path(File.dirname "#{(__FILE__)}/../lib")
if File.exist?(lib_path) && !$LOAD_PATH.include?(lib_path)
  $LOAD_PATH << lib_path
end

require 'sym'
require 'sym/crypt'
require 'sym/app'

begin
  exit ::Sym::App::CLI.new(ARGV.dup).execute
rescue Interrupt => e
  STDERR.flush
  STDERR.puts "Interrupt, #{e.message}, exiting."
  STDERR.flush
  exit 1
end

